version: 2

models:
  - name: youtubedata
    description: >
      The 'youtubedata' dataset provides comprehensive information on channels created in the year 2023, offering insights into their performance and success metrics. The primary objective is to analyze and identify the most successful YouTube newcomers based on factors such as the number of videos posted, accumulated views, and subscriber count.

    columns:
      - name: id
        description: >
          Primary key for this table, representing the unique identifier assigned to the channel by YouTube. Ensures data integrity and uniqueness.
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: title
        description: >
          The title or name of the channel, serving as a convenient reference for easy identification.

      - name: publishedate
        description: >
          The date when the channel was created, with the timestamp dependent on the region where the channel originated.
        tests:
          - not_null:
              severity: warn

      - name: country
        description: >
          The country associated with the channel, as provided by the channel's creator or owner. This information adds context to the channel's origin and audience demographics.

      - name: videos
        description: >
          The total number of videos uploaded by the user, serving as a key indicator of the channel's content production and activity.

      - name: views
        description: >
          The total number of views accumulated by the user from the videos posted, reflecting the channel's overall popularity and audience engagement.

      - name: subscribers
        description: >
          The total number of users who have subscribed to this channel, providing a crucial metric for assessing the channel's audience loyalty, engagement, and reach.
